<?php


namespace App\Http\Traits;


trait IconTrait {

    public function iconArray() {

        return array(
            "Airbnb",
            "Amazon Music",
            "Among Us",
            "Apple Music",
            "AutoTrader",
            "Behance",
            "Big Cartel",
            "Blogger",
            "CarGurus",
            "Cars",
            "CashApp",
            "Craigslist",
            "Depop",
            "Discord",
            "DoorDash",
            "Dropbox",
            "Ebay",
            "EbayMotors",
            "Email",
            "Etsy",
            "Facebook",
            "Facetime",
            "Fiverr",
            "Flickr",
            "Gmail",
            "Google Drive",
            "Google Earth",
            "Google Photos",
            "GoogleChat",
            "GoogleMaps",
            "GrubHub",
            "ICQ",
            "InstaCart",
            "Instagram",
            "Life360",
            "LinkedIn",
            "Marketplace",
            "Medium",
            "Messenger",
            "MicrosoftTeams",
            "OfferUp",
            "OneDrive",
            "OnlyFans",
            "OpenTable",
            "Outlook",
            "Pandora",
            "Patreon",
            "Paypal",
            "Phone",
            "PhotoBucket",
            "Picasa",
            "Pinterest",
            "Poshmark",
            "Postmates",
            "Quora",
            "Reddit",
            "Roblox",
            "RSS Feed",
            "Shopify",
            "Skype",
            "Slack",
            "Snapchat",
            "Soundcloud",
            "Spotify",
            "Telegram",
            "TikTok",
            "TripAdvisor",
            "Tumblr",
            "Twitch",
            "Twitter",
            "UberEats",
            "UpWork",
            "Venmo",
            "Viber",
            "Vimeo",
            "Whatsapp",
            "Wikipedia",
            "Xbox",
            "Yahoo Mail",
            "Yelp",
            "YouTube",
            "Zelle",
            "Zillow",
        );
    }
}
